dist: xenial

services:
  - postgresql

language: scala

scala:
  - 2.12.10
  - 2.13.0

before_install:
  - get fetch --tags
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass

stages:
  - init
  - test
  - docs
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: "Tests"
      name: Init
      script:
        - ./script/travis_init.sh
        - npm i -g yarn gulp-cli
        - sbt exampleServerJVM/stage
      - script:
          - echo "Starting integration test script"
          - ./all_tests.sh
    - stage: "Docs"
      script:
        - sbt docs/mdoc
        - sbt docs/docusaurusCreateSite
        if: TRAVIS_SCALA_VERSION == "2.12.10"
    - stage: "Release"
      script: sbt ci-release

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./website/build/http4s-modules
  target-branch: gh-pages
  on:
    branch: master


cache:
  directories:
    - "$HOME/.coursier/cache"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"