dist: xenial

services:
  - postgresql

language: scala

scala:
   - 2.12.8

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass

before_script:
  ./script/travis_init.sh
  npm i -g npm@8
  npm i -g yarn gulp-cli

jobs:
  include:
    script:
      - sbt test
      - sbt docs/mdoc
      - sbt docs/docusaurusCreateSite
      - cd website && yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./website/build
  target-branch: gh-pages
  on:
    branch: master
